import axios from "axios";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductFeed from "../components/ProductFeed";
import { ShoppingCartContext } from "../context/ShoppingCartContext";
export default function Home() {
  const { products } = useContext(ShoppingCartContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className=" flex flex-col space-y-10 absolute top-[6vh]">
        <Banner />
        <ProductFeed products={products} />
      </div>
    </>
  );
}
